# Generated by Django 3.2.2 on 2021-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210606_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiveType',
            field=models.CharField(default='patient', max_length=100),
        ),
    ]
