# Generated by Django 3.2.2 on 2021-06-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_message_receivetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recevier',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiveType',
            new_name='receivertype',
        ),
    ]
