# Generated by Django 3.2.2 on 2021-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210606_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msgread',
            field=models.BooleanField(default=False),
        ),
    ]
