# Generated by Django 3.2.2 on 2021-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message_msgread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msgread',
            field=models.CharField(default='', max_length=100),
        ),
    ]
