# Generated by Django 3.2.2 on 2021-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msgread',
            field=models.BooleanField(default=False),
        ),
    ]
