# Generated by Django 3.2.2 on 2021-06-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_message_msgread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiveruser', models.CharField(max_length=255)),
                ('msgread', models.BooleanField(default=False)),
                ('status', models.CharField(default='offline', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='msgread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
