# Generated by Django 3.2.2 on 2021-06-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210618_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='last_login',
            new_name='last_seen',
        ),
    ]
