# Generated by Django 3.2.2 on 2021-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_last_login_message_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_seen',
            field=models.DateTimeField(),
        ),
    ]
