# Generated by Django 3.2.2 on 2021-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_message_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_seen',
            field=models.CharField(default='2021-06-18 18:16:42.772296+05:30', max_length=255),
        ),
    ]
